apiVersion: v1
kind: ConfigMap
metadata:
  name: git-bot-config
  namespace: git-bot
  labels:
    app.kubernetes.io/name: git-bot
    app.kubernetes.io/component: app
data:
  LOG_LEVEL: "info"
  NODE_ENV: "production"
  INCIDENT_LABEL: "incident"
